apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
  annotations:
    {{- if .Values.path }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: "{{ if .Values.path }}{{ printf "%s(/|$)(.*)" .Values.path }}{{ else}}/{{ end }}"
          backend:
            service:
              name: {{ .Chart.Name }}
              port: 
                number: {{ .Values.servicePort }}
---